# Generated by Django 2.2.5 on 2020-10-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifyEmail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
