# Generated by Django 2.2.5 on 2020-10-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_user_verifyemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifyEmail',
        ),
    ]
